# Generated by Django 5.0.6 on 2024-07-06 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensajeria', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='canal',
            name='nombre',
        ),
        migrations.AddField(
            model_name='canal',
            name='asunto',
            field=models.CharField(default='Sin Asunto', max_length=100),
        ),
    ]
